/**
 * Design tokens shared by the config layer (event catalog) and the render layer.
 * Kept outside `src/bot` so `src/config` never has to import from `src/bot`.
 */

export const ACCENT_KEYS = [
	"neutral",
	"push",
	"branch",
	"tagRef",
	"delete",
	"prOpen",
	"prDraft",
	"prMerged",
	"prClosed",
	"review",
	"reviewApproved",
	"reviewChanges",
	"comment",
	"issueOpen",
	"issueClosed",
	"issueNotPlanned",
	"label",
	"milestone",
	"release",
	"prerelease",
	"packageAccent",
	"workflowRunning",
	"workflowSuccess",
	"workflowFailure",
	"workflowCancelled",
	"deployment",
	"deploymentSuccess",
	"deploymentFailure",
	"security",
	"securityCritical",
	"securityResolved",
	"discussion",
	"discussionAnswered",
	"fork",
	"star",
	"sponsor",
	"member",
	"wiki",
	"project",
	"repoMeta",
	"key",
] as const;

export type AccentKey = (typeof ACCENT_KEYS)[number];

export const ICON_KEYS = [
	"push",
	"commit",
	"branch",
	"tagRef",
	"trash",
	"pullRequest",
	"pullRequestDraft",
	"merged",
	"closed",
	"review",
	"approved",
	"changesRequested",
	"comment",
	"issue",
	"issueClosed",
	"label",
	"milestone",
	"release",
	"packageIcon",
	"workflow",
	"success",
	"failure",
	"cancelled",
	"running",
	"deployment",
	"rocket",
	"shield",
	"alert",
	"discussion",
	"answered",
	"fork",
	"star",
	"sponsor",
	"person",
	"wiki",
	"project",
	"repo",
	"key",
	"globe",
	"gear",
	"clock",
	"github",
] as const;

export type IconKey = (typeof ICON_KEYS)[number];
